package ie.stephen.service;

import ie.stephen.dao.CustomerDao;
import ie.stephen.model.Customer;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.stereotype.Service;

@Service
public class CustomerServiceImplementation implements CustomerService {

    @Autowired
    CustomerDao customerDao;

    public void newCustomer(String firstName, String lastName) {
        try {
            int customerId = customerDao.newCustomer(firstName, lastName);
            System.out.println("Customer account created for " + firstName + " " + lastName +
                    ". Your id is " + customerId);
        }
        catch (NullPointerException ex) {
            System.out.println("ERROR: Failed to find autogenerated customer id");
        }
    }

    public boolean exists(int customerId) {
        try {
            customerDao.findById(customerId);
        }
        catch (EmptyResultDataAccessException ex) {
            System.out.println("Customer not found");
            return false;
        }
        return true;
    }

    public boolean displayInfo(int customerId) {
        try {
            Customer customer = customerDao.findById(customerId);
            System.out.println(customer.toString());
        } catch (EmptyResultDataAccessException ex) {
            System.out.println("Customer not found");
            return false;
        }
        return true;
    }
}
